### ISSUE TITLE
Unable to get Cypress GUI to appear on local machine from Docker container

### ISSUE THREAD

**Issue by ptrk8** [bahmutov/cypress-open-from-docker-compose#4]
I've been following the instructions from [this page](https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/); however, I'm unable to get the test runner to launch locally on my machine.

When I run the following command:

` docker-compose -f docker-compose.yml -f cy-open.yml up --exit-code-from cypress`

I receive the following output and my docker container shuts down:

> WARNING: using --exit-code-from implies --abort-on-container-exit
> Starting e2e_sentimentalyzer_1 ... done
> Recreating e2e_cypress_1       ... done
> Attaching to e2e_sentimentalyzer_1, e2e_cypress_1
> sentimentalyzer_1  | 2019/11/06 13:17:18 Listening on port 8123
> e2e_cypress_1 exited with code 0
> Aborting on container exit...
> Stopping e2e_sentimentalyzer_1 ... done

**Steps that I have taken**

I followed the instructions on [this page](https://sourabhbajaj.com/blog/2017/02/07/gui-applications-docker-mac/), which outlines the setup that is required to get XQuartz to work with Docker containers.

- Specifically, I adjusted my security preferences in XQuartz to "Allow connections from network clients".
- I entered the following command to set IP variable as the IP of my local machine.

`IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')`

- I ran `xhost + $IP` to add the IP using XHost.

To ensure that I had done everything correctly, I then ran the following command in my terminal.

`docker run -d --name firefox -e DISPLAY=$IP:0 -v /tmp/.X11-unix:/tmp/.X11-unix jess/firefox`

Running this command successfully launched a Firefox browser in XQuartz, which reassured me that I had correctly followed those instructions.

I then cloned this repository and ran the following commands as per the README.
```
cd e2e
docker-compose -f docker-compose.yml -f cy-open.yml up --exit-code-from cypress
```
Unfortunately, I get the error I described above.

**Things I've tried**

The cy-open.yml file contains the following comments.

```
    environment:
      # get the IP address of the host machine and allow X11 to accept
      # incoming connections from that IP address
      #   IP=$(ipconfig getifaddr en0)
      #   /usr/X11/bin/xhost + $IP
      # then pass the environment variable DISPLAY to show Cypress GUI on the host system
      #   DISPLAY=$IP:0
      - DISPLAY
```
So I decided to run the following command in my terminal to set the DISPLAY variable to my local IP address appended by ":0". Unfortunately, this didn't fix the issue.

`DISPLAY=$IP:0`

I also experimented by hardcoding the value of $IP:0 in the DISPLAY environment variable in the cy-open.yml file as shown below. Unfortunately, this also didn't fix the issue.

```
    environment:
      - DISPLAY=<My IP address here>:0
```
As I'm quite new to Docker and I'm fairly unfamiliar with XQuartz, I can't seem to figure out why I'm unable to replicate your tutorial, which I've tried to follow verbatim. Is there something obvious that I'm missing? My machine is running MacOS High Sierra 10.13.5.

**Comment by KaleabTessera** [comment]
What was the solution to this?
